QUESTION_BANK = {'intro': [{'id': 'intro_q1',
            'prompt': 'Ποιος είναι ο κύριος ρόλος της JavaScript σε μία ιστοσελίδα;',
            'options': ['Να προσθέτει διαδραστική συμπεριφορά',
                        'Να αντικαθιστά το λειτουργικό σύστημα',
                        'Να συμπιέζει εικόνες'],
            'answer': 'Να προσθέτει διαδραστική συμπεριφορά',
            'hint': 'Σκέψου τι γίνεται όταν ο χρήστης πατά ένα κουμπί.',
            'explanation': 'Η JavaScript χρησιμοποιείται κυρίως για συμπεριφορά και αλληλεπίδραση μέσα στη σελίδα.'},
           {'id': 'intro_q2',
            'prompt': 'Ποια τεχνολογία περιγράφει κυρίως τη δομή μιας σελίδας;',
            'options': ['HTML', 'CSS', 'JavaScript'],
            'answer': 'HTML',
            'hint': 'Είναι η γλώσσα με tags όπως h1, p και button.',
            'explanation': 'Η HTML οργανώνει το περιεχόμενο και τη δομή της σελίδας.'},
           {'id': 'intro_q3',
            'prompt': "Τι εμφανίζει η εντολή console.log('test');",
            'options': ['Μήνυμα στην κονσόλα', 'Νέο αρχείο', 'CSS κανόνα'],
            'answer': 'Μήνυμα στην κονσόλα',
            'hint': 'Η console βοηθά στον έλεγχο και στο debugging.',
            'explanation': 'Η console.log γράφει μήνυμα στην κονσόλα.'},
           {'id': 'intro_q4',
            'prompt': 'Ποια τεχνολογία καθορίζει χρώματα και γραμματοσειρές;',
            'options': ['CSS', 'HTML', 'SQLite'],
            'answer': 'CSS',
            'hint': 'Αφορά την εμφάνιση.',
            'explanation': 'Η CSS είναι υπεύθυνη για την οπτική μορφοποίηση.'},
           {'id': 'intro_q5',
            'prompt': 'Ποιο είναι παράδειγμα διαδραστικότητας;',
            'options': ['Εμφάνιση μηνύματος μετά από click', 'Αποθήκευση εικόνας σε φάκελο', 'Αλλαγή ανάλυσης οθόνης'],
            'answer': 'Εμφάνιση μηνύματος μετά από click',
            'hint': 'Συνδέεται με ενέργεια χρήστη.',
            'explanation': 'Το click και η αντίδραση της σελίδας είναι διαδραστικότητα.'},
           {'id': 'intro_q6',
            'prompt': 'Πού μπορείς να δεις μηνύματα console.log στον browser;',
            'options': ['Στην κονσόλα developer tools', 'Στο αρχείο CSS', 'Στη βάση δεδομένων πάντα'],
            'answer': 'Στην κονσόλα developer tools',
            'hint': 'Άνοιξε τα εργαλεία προγραμματιστή.',
            'explanation': 'Τα console.log εμφανίζονται στην κονσόλα των developer tools.'}],
 'basics': [{'id': 'basics_q1',
             'prompt': 'Πότε προτιμάμε const αντί για let;',
             'options': ['Όταν δεν θέλουμε νέα ανάθεση της μεταβλητής',
                         'Όταν γράφουμε μόνο αριθμούς',
                         'Όταν θέλουμε υποχρεωτικά global μεταβλητή'],
             'answer': 'Όταν δεν θέλουμε νέα ανάθεση της μεταβλητής',
             'hint': 'Το const δηλώνει σταθερή αναφορά.',
             'explanation': 'Το const είναι κατάλληλο όταν δεν θα γίνει νέα ανάθεση.'},
            {'id': 'basics_q2',
             'prompt': 'Τι επιστρέφει η έκφραση 7 >= 5;',
             'options': ['true', 'false', "'7 >= 5'"],
             'answer': 'true',
             'hint': 'Είναι σύγκριση αριθμών.',
             'explanation': 'Το 7 είναι μεγαλύτερο ή ίσο με το 5.'},
            {'id': 'basics_q3',
             'prompt': 'Τι τύπος είναι το αποτέλεσμα μιας σύγκρισης;',
             'options': ['boolean', 'array', 'object πάντα'],
             'answer': 'boolean',
             'hint': 'Οι τιμές είναι true ή false.',
             'explanation': 'Οι συγκρίσεις επιστρέφουν boolean.'},
            {'id': 'basics_q4',
             'prompt': 'Ποιος τελεστής ελέγχει τιμή και τύπο;',
             'options': ['===', '=', '=>'],
             'answer': '===',
             'hint': 'Είναι αυστηρή ισότητα.',
             'explanation': 'Το === ελέγχει και τιμή και τύπο.'},
            {'id': 'basics_q5',
             'prompt': 'Ποια δομή χρησιμοποιούμε για απόφαση;',
             'options': ['if/else', 'font-size', 'href'],
             'answer': 'if/else',
             'hint': 'Εκτελεί διαφορετικό κώδικα ανά συνθήκη.',
             'explanation': 'Το if/else επιτρέπει αποφάσεις.'},
            {'id': 'basics_q6',
             'prompt': "Τι τύπος είναι η τιμή 'Μαρία';",
             'options': ['string', 'number', 'boolean'],
             'answer': 'string',
             'hint': 'Είναι κείμενο.',
             'explanation': 'Οι τιμές μέσα σε εισαγωγικά είναι strings.'}],
 'functions': [{'id': 'functions_q1',
                'prompt': 'Γιατί χρησιμοποιούμε συναρτήσεις;',
                'options': ['Για οργάνωση και επαναχρησιμοποίηση κώδικα',
                            'Για να κρύβουμε λάθη',
                            'Για να γράφουμε CSS'],
                'answer': 'Για οργάνωση και επαναχρησιμοποίηση κώδικα',
                'hint': 'Ομαδοποιούν λογική.',
                'explanation': 'Οι συναρτήσεις κάνουν τον κώδικα καθαρότερο.'},
               {'id': 'functions_q2',
                'prompt': 'Ποια λέξη επιστρέφει αποτέλεσμα από συνάρτηση;',
                'options': ['return', 'repeat', 'send'],
                'answer': 'return',
                'hint': 'Βγάζει τιμή από τη συνάρτηση.',
                'explanation': 'Η return επιστρέφει τιμή.'},
               {'id': 'functions_q3',
                'prompt': 'Στο function hello(name), τι είναι το name;',
                'options': ['parameter', 'argument', 'CSS selector'],
                'answer': 'parameter',
                'hint': 'Είναι το όνομα μέσα στον ορισμό.',
                'explanation': 'Το name είναι parameter.'},
               {'id': 'functions_q4',
                'prompt': "Στο hello('Άννα'), τι είναι το 'Άννα';",
                'options': ['argument', 'parameter', 'boolean'],
                'answer': 'argument',
                'hint': 'Είναι η πραγματική τιμή.',
                'explanation': "Το 'Άννα' είναι argument."},
               {'id': 'functions_q5',
                'prompt': 'Ποιο σύμβολο χαρακτηρίζει arrow function;',
                'options': ['=>', '===', '#'],
                'answer': '=>',
                'hint': 'Μοιάζει με βέλος.',
                'explanation': 'Το => χρησιμοποιείται στις arrow functions.'},
               {'id': 'functions_q6',
                'prompt': 'Τι είναι καλύτερο για επαναχρησιμοποιήσιμο αποτέλεσμα;',
                'options': ['return', 'console.log μόνο', 'alert πάντα'],
                'answer': 'return',
                'hint': 'Το αποτέλεσμα μπορεί να χρησιμοποιηθεί αλλού.',
                'explanation': 'Το return επιτρέπει επαναχρήση αποτελέσματος.'}],
 'arrays': [{'id': 'arrays_q1',
             'prompt': 'Τι είναι array;',
             'options': ['Λίστα τιμών', 'CSS χρώμα', 'HTML tag'],
             'answer': 'Λίστα τιμών',
             'hint': 'Περιέχει πολλά στοιχεία.',
             'explanation': 'Το array αποθηκεύει πολλές τιμές.'},
            {'id': 'arrays_q2',
             'prompt': 'Ποιο είναι το πρώτο index ενός array;',
             'options': ['0', '1', '-1'],
             'answer': '0',
             'hint': 'Η JavaScript μετρά από το μηδέν.',
             'explanation': 'Τα arrays ξεκινούν από index 0.'},
            {'id': 'arrays_q3',
             'prompt': 'Ποιο method κρατά στοιχεία που περνούν κριτήριο;',
             'options': ['filter', 'map', 'parse'],
             'answer': 'filter',
             'hint': 'Φιλτράρει.',
             'explanation': 'Το filter κρατά στοιχεία με βάση συνθήκη.'},
            {'id': 'arrays_q4',
             'prompt': 'Ποιο method δημιουργεί νέο array μετασχηματίζοντας τιμές;',
             'options': ['map', 'filter', 'alert'],
             'answer': 'map',
             'hint': 'Χαρτογραφεί κάθε στοιχείο σε νέα τιμή.',
             'explanation': 'Το map επιστρέφει νέο array.'},
            {'id': 'arrays_q5',
             'prompt': 'Ποιο method μπορεί να υπολογίσει άθροισμα;',
             'options': ['reduce', 'querySelector', 'JSON.parse'],
             'answer': 'reduce',
             'hint': 'Μειώνει array σε μία τιμή.',
             'explanation': 'Το reduce μπορεί να παράγει άθροισμα.'},
            {'id': 'arrays_q6',
             'prompt': 'Τι δείχνει το scores.length;',
             'options': ['Το πλήθος στοιχείων', 'Το πρώτο στοιχείο', 'Το χρώμα του array'],
             'answer': 'Το πλήθος στοιχείων',
             'hint': 'length σημαίνει μήκος.',
             'explanation': 'Το length επιστρέφει πλήθος στοιχείων.'}],
 'objects': [{'id': 'objects_q1',
              'prompt': 'Τι αναπαριστά ένα object;',
              'options': ['Οντότητα με ιδιότητες', 'Μόνο αριθμό', 'CSS κανόνα'],
              'answer': 'Οντότητα με ιδιότητες',
              'hint': 'Έχει key/value.',
              'explanation': 'Τα objects έχουν properties.'},
             {'id': 'objects_q2',
              'prompt': 'Πώς διαβάζουμε το name από student;',
              'options': ['student.name', 'student-name', 'student#name'],
              'answer': 'student.name',
              'hint': 'Dot notation.',
              'explanation': 'Με dot notation διαβάζουμε properties.'},
             {'id': 'objects_q3',
              'prompt': 'Τι κάνει το JSON.stringify;',
              'options': ['Μετατρέπει object σε JSON string', 'Αλλάζει CSS', 'Σβήνει array'],
              'answer': 'Μετατρέπει object σε JSON string',
              'hint': 'stringify σημαίνει μετατροπή σε string.',
              'explanation': 'Το JSON.stringify παράγει JSON text.'},
             {'id': 'objects_q4',
              'prompt': 'Τι κάνει το JSON.parse;',
              'options': ['Μετατρέπει JSON string σε τιμή JavaScript', 'Δημιουργεί event', 'Μετρά pixels'],
              'answer': 'Μετατρέπει JSON string σε τιμή JavaScript',
              'hint': 'parse σημαίνει ανάλυση κειμένου.',
              'explanation': 'Το JSON.parse διαβάζει JSON string.'},
             {'id': 'objects_q5',
              'prompt': 'Τι είναι property;',
              'options': ['Ιδιότητα object', 'Loop', 'Browser tab'],
              'answer': 'Ιδιότητα object',
              'hint': 'Π.χ. name ή score.',
              'explanation': 'Property είναι ιδιότητα σε object.'},
             {'id': 'objects_q6',
              'prompt': 'Ποια σύνταξη είναι destructuring;',
              'options': ['const { name } = student', 'const name => student', '#student.name'],
              'answer': 'const { name } = student',
              'hint': 'Χρησιμοποιεί άγκιστρα.',
              'explanation': 'Αυτή είναι σύνταξη object destructuring.'}],
 'dom_async': [{'id': 'dom_q1',
                'prompt': "Τι κάνει το document.querySelector('#title');",
                'options': ['Βρίσκει το πρώτο στοιχείο με id title', 'Δημιουργεί βάση', 'Σβήνει κουμπιά'],
                'answer': 'Βρίσκει το πρώτο στοιχείο με id title',
                'hint': 'Το # είναι selector για id.',
                'explanation': 'Το querySelector επιστρέφει DOM στοιχείο.'},
               {'id': 'dom_q2',
                'prompt': 'Ποιο event χρησιμοποιούμε για πάτημα κουμπιού;',
                'options': ['click', 'paint', 'loadData'],
                'answer': 'click',
                'hint': 'Περιγράφει πάτημα.',
                'explanation': 'Το click ενεργοποιείται με πάτημα.'},
               {'id': 'dom_q3',
                'prompt': 'Γιατί χρησιμοποιούμε preventDefault σε form submit;',
                'options': ['Για να μη γίνει αυτόματη ανανέωση σελίδας',
                            'Για να αλλάξει χρώμα',
                            'Για να φτιαχτεί array'],
                'answer': 'Για να μη γίνει αυτόματη ανανέωση σελίδας',
                'hint': 'Ελέγχουμε τη φόρμα με JS.',
                'explanation': 'Το preventDefault σταματά την προεπιλεγμένη συμπεριφορά.'},
               {'id': 'dom_q4',
                'prompt': 'Τι επιστρέφει συνήθως η fetch;',
                'options': ['Promise', 'CSS file', 'HTML tag'],
                'answer': 'Promise',
                'hint': 'Ασύγχρονη λειτουργία.',
                'explanation': 'Η fetch επιστρέφει Promise.'},
               {'id': 'dom_q5',
                'prompt': 'Ποια ιδιότητα αλλάζει κείμενο DOM στοιχείου;',
                'options': ['textContent', 'serverPort', 'databaseName'],
                'answer': 'textContent',
                'hint': 'Περιεχόμενο κειμένου.',
                'explanation': 'Το textContent αλλάζει κείμενο.'},
               {'id': 'dom_q6',
                'prompt': 'Τι κάνει το await;',
                'options': ['Περιμένει Promise μέσα σε async function', 'Δηλώνει CSS', 'Δημιουργεί object'],
                'answer': 'Περιμένει Promise μέσα σε async function',
                'hint': 'Συνδέεται με async.',
                'explanation': 'Το await περιμένει ολοκλήρωση Promise.'}],
 'debug_project': [{'id': 'debug_q1',
                    'prompt': 'Τι είναι syntax error;',
                    'options': ['Λάθος γραμματικής κώδικα', 'Χρώμα CSS', 'Επιτυχές quiz'],
                    'answer': 'Λάθος γραμματικής κώδικα',
                    'hint': 'Ο κώδικας δεν μπορεί να διαβαστεί σωστά.',
                    'explanation': 'Syntax error σημαίνει λάθος σύνταξης.'},
                   {'id': 'debug_q2',
                    'prompt': 'Ποιο εργαλείο βοηθά να δεις τιμή μεταβλητής;',
                    'options': ['console.log', 'border-radius', 'href'],
                    'answer': 'console.log',
                    'hint': 'Εμφανίζει στην κονσόλα.',
                    'explanation': 'Το console.log βοηθά στον έλεγχο τιμών.'},
                   {'id': 'debug_q3',
                    'prompt': 'Τι είναι state εφαρμογής;',
                    'options': ['Τα δεδομένα της τρέχουσας κατάστασης', 'Μόνο εικόνα', 'CSS font'],
                    'answer': 'Τα δεδομένα της τρέχουσας κατάστασης',
                    'hint': 'Π.χ. ενεργή ενότητα και score.',
                    'explanation': 'State είναι η τρέχουσα κατάσταση δεδομένων.'},
                   {'id': 'debug_q4',
                    'prompt': 'Πού κοιτάμε συχνά όταν κάτι δεν δουλεύει στον browser;',
                    'options': ['Developer console', 'Μόνο στο wallpaper', 'Στο πληκτρολόγιο'],
                    'answer': 'Developer console',
                    'hint': 'Εμφανίζει errors.',
                    'explanation': 'Η κονσόλα δείχνει σφάλματα και logs.'},
                   {'id': 'debug_q5',
                    'prompt': 'Τι πρέπει να έχει ένα ολοκληρωμένο quiz app;',
                    'options': ['Ερωτήσεις, υποβολή, score και feedback', 'Μόνο χρώμα φόντου', 'Μόνο τίτλο'],
                    'answer': 'Ερωτήσεις, υποβολή, score και feedback',
                    'hint': 'Σκέψου τη ροή χρήστη.',
                    'explanation': 'Ένα quiz app χρειάζεται περιεχόμενο, αλληλεπίδραση και ανατροφοδότηση.'},
                   {'id': 'debug_q6',
                    'prompt': 'Ποια στρατηγική είναι χρήσιμη στο debugging;',
                    'options': ['Έλεγχος μικρών βημάτων', 'Τυχαίες αλλαγές παντού', 'Διαγραφή όλου του κώδικα'],
                    'answer': 'Έλεγχος μικρών βημάτων',
                    'hint': 'Απομονώνουμε το πρόβλημα.',
                    'explanation': 'Το debugging γίνεται καλύτερα με μικρά, ελεγχόμενα βήματα.'}]}


QUESTION_BANK['intro'].extend([
  {'id': 'intro_q7',
   'prompt': 'Ποια είναι σωστή σειρά για μία απλή αλληλεπίδραση;',
   'options': ['Επιλογή στοιχείου, event, αλλαγή περιεχομένου', 'CSS, SQL, εκτύπωση PDF', 'Διαγραφή HTML, μετά click'],
   'answer': 'Επιλογή στοιχείου, event, αλλαγή περιεχομένου',
   'hint': 'Σκέψου τι γίνεται όταν πατάς κουμπί.',
   'explanation': 'Η JavaScript συνήθως βρίσκει στοιχείο, ακούει event και αλλάζει τη σελίδα.'},
  {'id': 'intro_q8',
   'prompt': 'Πότε είναι πιο σωστό να χρησιμοποιηθεί CSS αντί για JavaScript;',
   'options': ['Για αλλαγή χρώματος κουμπιού', 'Για έλεγχο απάντησης quiz', 'Για αποθήκευση προόδου'],
   'answer': 'Για αλλαγή χρώματος κουμπιού',
   'hint': 'Η CSS αφορά κυρίως εμφάνιση.',
   'explanation': 'Η εμφάνιση, όπως χρώματα και γραμματοσειρές, ανήκει κυρίως στην CSS.'}
])

QUESTION_BANK['basics'].extend([
  {'id': 'basics_q7',
   'prompt': "Γιατί το '10' === 10 επιστρέφει false;",
   'options': ['Επειδή έχουν διαφορετικό τύπο', 'Επειδή το 10 είναι μικρότερο', 'Επειδή λείπει CSS'],
   'answer': 'Επειδή έχουν διαφορετικό τύπο',
   'hint': 'Το ένα είναι string και το άλλο number.',
   'explanation': 'Το === ελέγχει και τιμή και τύπο.'},
  {'id': 'basics_q8',
   'prompt': 'Πότε χρησιμοποιούμε else if;',
   'options': ['Όταν υπάρχουν περισσότερες από δύο περιπτώσεις', 'Μόνο για arrays', 'Μόνο μέσα σε CSS'],
   'answer': 'Όταν υπάρχουν περισσότερες από δύο περιπτώσεις',
   'hint': 'Σκέψου επίπεδα feedback.',
   'explanation': 'Το else if επιτρέπει πολλαπλά επίπεδα απόφασης.'}
])

QUESTION_BANK['functions'].extend([
  {'id': 'functions_q7',
   'prompt': 'Ποιο είναι πλεονέκτημα μίας καθαρής συνάρτησης;',
   'options': ['Είναι πιο εύκολη στον έλεγχο', 'Αλλάζει πάντα global μεταβλητές', 'Χρειάζεται πάντα alert'],
   'answer': 'Είναι πιο εύκολη στον έλεγχο',
   'hint': 'Το ίδιο input δίνει ίδιο output.',
   'explanation': 'Οι καθαρές συναρτήσεις είναι πιο προβλέψιμες και ελέγχονται ευκολότερα.'},
  {'id': 'functions_q8',
   'prompt': 'Γιατί χωρίζουμε ένα μεγάλο πρόβλημα σε μικρές συναρτήσεις;',
   'options': ['Για καθαρότερο και επαναχρησιμοποιήσιμο κώδικα', 'Για να κρύψουμε το HTML', 'Για να μη γράφουμε μεταβλητές'],
   'answer': 'Για καθαρότερο και επαναχρησιμοποιήσιμο κώδικα',
   'hint': 'Κάθε συνάρτηση κάνει μία δουλειά.',
   'explanation': 'Η διάσπαση κάνει την υλοποίηση πιο οργανωμένη και συντηρήσιμη.'}
])

QUESTION_BANK['arrays'].extend([
  {'id': 'arrays_q7',
   'prompt': 'Τι κάνει το map σε έναν πίνακα;',
   'options': ['Δημιουργεί νέο πίνακα με μετασχηματισμένες τιμές', 'Σβήνει τη βάση', 'Ανοίγει νέο browser tab'],
   'answer': 'Δημιουργεί νέο πίνακα με μετασχηματισμένες τιμές',
   'hint': 'Μετατρέπει κάθε στοιχείο.',
   'explanation': 'Το map εφαρμόζει συνάρτηση σε κάθε στοιχείο και επιστρέφει νέο array.'},
  {'id': 'arrays_q8',
   'prompt': 'Γιατί χρησιμοποιούμε join μετά από map που φτιάχνει HTML strings;',
   'options': ['Για να ενώσουμε τα strings σε ένα HTML κείμενο', 'Για να κάνουμε login', 'Για να αλλάξουμε database schema'],
   'answer': 'Για να ενώσουμε τα strings σε ένα HTML κείμενο',
   'hint': 'Το map επιστρέφει array.',
   'explanation': 'Το join ενώνει τα στοιχεία του array σε ένα string που μπορεί να μπει στο DOM.'}
])

QUESTION_BANK['objects'].extend([
  {'id': 'objects_q7',
   'prompt': 'Γιατί ένα quiz question είναι καλό να είναι object;',
   'options': ['Για να κρατά prompt, options, answer και hint μαζί', 'Για να γίνει CSS πιο μικρή', 'Για να μη χρειάζεται JavaScript'],
   'answer': 'Για να κρατά prompt, options, answer και hint μαζί',
   'hint': 'Όλα ανήκουν στην ίδια ερώτηση.',
   'explanation': 'Το object οργανώνει σχετικές πληροφορίες σε μία δομή.'},
  {'id': 'objects_q8',
   'prompt': 'Τι είναι nested object;',
   'options': ['Object που περιέχει άλλο object', 'Object χωρίς properties', 'Μόνο αριθμός'],
   'answer': 'Object που περιέχει άλλο object',
   'hint': 'Π.χ. student.progress.average.',
   'explanation': 'Τα nested objects επιτρέπουν πιο σύνθετη μοντελοποίηση δεδομένων.'}
])

QUESTION_BANK['dom_async'].extend([
  {'id': 'dom_q7',
   'prompt': 'Τι περιγράφει το state μίας εφαρμογής;',
   'options': ['Την τρέχουσα κατάσταση δεδομένων και UI', 'Μόνο το χρώμα φόντου', 'Μόνο το όνομα αρχείου CSS'],
   'answer': 'Την τρέχουσα κατάσταση δεδομένων και UI',
   'hint': 'Π.χ. ενεργή ενότητα και χρήστης.',
   'explanation': 'Το state κρατά πληροφορίες που επηρεάζουν τι εμφανίζει η εφαρμογή.'},
  {'id': 'dom_q8',
   'prompt': 'Γιατί χρειάζεται try/catch σε async κλήσεις;',
   'options': ['Για χειρισμό αποτυχημένης φόρτωσης ή server error', 'Για να μεγαλώσει το font', 'Για να γίνει το array object'],
   'answer': 'Για χειρισμό αποτυχημένης φόρτωσης ή server error',
   'hint': 'Οι κλήσεις δικτύου μπορεί να αποτύχουν.',
   'explanation': 'Το try/catch επιτρέπει καθαρό feedback όταν μία async λειτουργία αποτύχει.'}
])

QUESTION_BANK['debug_project'].extend([
  {'id': 'debug_q7',
   'prompt': 'Ποια ροή πρέπει να ελεγχθεί πριν παραδοθεί η εφαρμογή;',
   'options': ['Εγγραφή, είσοδος, quiz, αναφορές, αποσύνδεση', 'Μόνο αλλαγή wallpaper', 'Μόνο μέγεθος παραθύρου'],
   'answer': 'Εγγραφή, είσοδος, quiz, αναφορές, αποσύνδεση',
   'hint': 'Σκέψου βασικές ενέργειες χρήστη.',
   'explanation': 'Η ποιότητα ελέγχεται με πλήρεις ροές χρήστη, όχι μόνο με μεμονωμένα κουμπιά.'},
  {'id': 'debug_q8',
   'prompt': 'Τι κάνει μία εφαρμογή πιο ολοκληρωμένο προϊόν;',
   'options': ['Περιεχόμενο, UI, αποθήκευση, feedback και τεκμηρίωση', 'Μόνο πολλά χρώματα', 'Μόνο ένα κουμπί'],
   'answer': 'Περιεχόμενο, UI, αποθήκευση, feedback και τεκμηρίωση',
   'hint': 'Δεν αρκεί να υπάρχει μόνο κώδικας.',
   'explanation': 'Ένα ολοκληρωμένο προϊόν χρειάζεται λειτουργικότητα, εμπειρία χρήστη και τεκμηρίωση.'}
])

QUESTION_BANK['storage'] = [
  {'id': 'storage_q1',
   'prompt': 'Πόσο διαρκεί συνήθως το sessionStorage;',
   'options': ['Όσο διαρκεί το browser tab', 'Για πάντα στον server', 'Μόνο για ένα δευτερόλεπτο'],
   'answer': 'Όσο διαρκεί το browser tab',
   'hint': 'Session σημαίνει συνεδρία.',
   'explanation': 'Το sessionStorage κρατά δεδομένα για τη διάρκεια του tab.'},
  {'id': 'storage_q2',
   'prompt': 'Πότε προτιμάμε SQLite/server αντί για browser storage;',
   'options': ['Για μόνιμη πρόοδο και λογαριασμούς', 'Για απλό χρώμα φόντου', 'Για CSS hover'],
   'answer': 'Για μόνιμη πρόοδο και λογαριασμούς',
   'hint': 'Σκέψου δεδομένα που πρέπει να μη χαθούν.',
   'explanation': 'Η μόνιμη και προσωπική πρόοδος πρέπει να αποθηκεύεται στη βάση.'},
  {'id': 'storage_q3',
   'prompt': 'Τι κάνει το JSON.stringify;',
   'options': ['Μετατρέπει object σε string', 'Σβήνει localStorage', 'Κάνει fetch'],
   'answer': 'Μετατρέπει object σε string',
   'hint': 'Storage αποθηκεύει κείμενο.',
   'explanation': 'Το JSON.stringify μετατρέπει object σε JSON text.'},
  {'id': 'storage_q4',
   'prompt': 'Τι κάνει το JSON.parse;',
   'options': ['Μετατρέπει JSON string σε τιμή JavaScript', 'Αλλάζει CSS', 'Δημιουργεί event'],
   'answer': 'Μετατρέπει JSON string σε τιμή JavaScript',
   'hint': 'Επαναφέρει αποθηκευμένο JSON.',
   'explanation': 'Το JSON.parse διαβάζει JSON text και επιστρέφει object/array/τιμή.'},
  {'id': 'storage_q5',
   'prompt': 'Ποια ενέργεια είναι σωστή στην αποσύνδεση;',
   'options': ['Καθαρισμός sessionStorage και επιστροφή στο login', 'Άνοιγμα quiz χωρίς χρήστη', 'Αποθήκευση κωδικού σε plain text'],
   'answer': 'Καθαρισμός sessionStorage και επιστροφή στο login',
   'hint': 'Ο χρήστης δεν πρέπει να μένει στην κύρια σελίδα.',
   'explanation': 'Η αποσύνδεση καθαρίζει τη συνεδρία και γυρίζει στην αρχική σελίδα.'},
  {'id': 'storage_q6',
   'prompt': 'Ποια μέθοδος αφαιρεί μία τιμή από sessionStorage;',
   'options': ['removeItem', 'filter', 'querySelector'],
   'answer': 'removeItem',
   'hint': 'Αφαιρεί item.',
   'explanation': 'Η removeItem διαγράφει συγκεκριμένο κλειδί από storage.'},
  {'id': 'storage_q7',
   'prompt': 'Ποια πληροφορία είναι καλύτερα να μη μένει μόνιμα στο localStorage;',
   'options': ['Ευαίσθητος κωδικός χρήστη', 'Θέμα εμφάνισης', 'Τελευταία ανοιχτή ενότητα χωρίς προσωπικά δεδομένα'],
   'answer': 'Ευαίσθητος κωδικός χρήστη',
   'hint': 'Σκέψου ασφάλεια.',
   'explanation': 'Οι κωδικοί δεν πρέπει να αποθηκεύονται μόνιμα και απροστάτευτα στον browser.'},
  {'id': 'storage_q8',
   'prompt': 'Γιατί χρησιμοποιούμε location.replace μετά την αποσύνδεση;',
   'options': ['Για να γυρίσει ο χρήστης στο login χωρίς να μένει στην ίδια ροή ιστορικού', 'Για να υποβληθεί quiz', 'Για να γίνει reduce'],
   'answer': 'Για να γυρίσει ο χρήστης στο login χωρίς να μένει στην ίδια ροή ιστορικού',
   'hint': 'Αφορά πλοήγηση.',
   'explanation': 'Το replace αντικαθιστά την τρέχουσα σελίδα με τη σελίδα login.'}
]

QUESTION_BANK['quality_project'] = [
  {'id': 'quality_q1',
   'prompt': 'Ποια είναι πλήρης ροή χρήστη στην εφαρμογή;',
   'options': ['Preview, login, study, quiz, report, logout', 'Μόνο login', 'Μόνο αλλαγή χρώματος'],
   'answer': 'Preview, login, study, quiz, report, logout',
   'hint': 'Σκέψου από την αρχική μέχρι την αποσύνδεση.',
   'explanation': 'Η ολοκληρωμένη εφαρμογή καλύπτει όλη τη διαδρομή χρήστη.'},
  {'id': 'quality_q2',
   'prompt': 'Τι πρέπει να ελέγχουμε πριν την παράδοση;',
   'options': ['Βασικές λειτουργικές ροές', 'Μόνο αν αρέσει το χρώμα', 'Μόνο αν υπάρχει τίτλος'],
   'answer': 'Βασικές λειτουργικές ροές',
   'hint': 'Εγγραφή, quiz, αναφορά.',
   'explanation': 'Ο έλεγχος ποιότητας αφορά λειτουργίες που πρέπει να δουλεύουν από άκρη σε άκρη.'},
  {'id': 'quality_q3',
   'prompt': 'Ποια σειρά είναι παιδαγωγικά σωστή;',
   'options': ['Θεωρία, παράδειγμα, εξάσκηση, quiz, feedback', 'Quiz πριν από θεωρία', 'Feedback χωρίς απάντηση'],
   'answer': 'Θεωρία, παράδειγμα, εξάσκηση, quiz, feedback',
   'hint': 'Πρώτα μαθαίνεις, μετά αξιολογείσαι.',
   'explanation': 'Η αξιολόγηση πρέπει να ακολουθεί τη διδασκαλία και την εξάσκηση.'},
  {'id': 'quality_q4',
   'prompt': 'Τι πρέπει να περιλαμβάνει η τεκμηρίωση;',
   'options': ['Περιγραφή, αρχεία, οδηγίες εκτέλεσης και λειτουργίες', 'Μόνο μία εικόνα', 'Μόνο CSS'],
   'answer': 'Περιγραφή, αρχεία, οδηγίες εκτέλεσης και λειτουργίες',
   'hint': 'Να μπορεί άλλος να τρέξει την εφαρμογή.',
   'explanation': 'Η τεκμηρίωση βοηθά στην κατανόηση και αξιολόγηση του έργου.'},
  {'id': 'quality_q5',
   'prompt': 'Ποια λειτουργία δείχνει ότι η πρόοδος αποθηκεύεται;',
   'options': ['Αναφορές με επίδοση, προσπάθειες και χρόνο', 'Μόνο στατικό κείμενο', 'Μόνο logo'],
   'answer': 'Αναφορές με επίδοση, προσπάθειες και χρόνο',
   'hint': 'Στατιστικά χρήστη.',
   'explanation': 'Οι αναφορές δείχνουν αποθηκευμένα στοιχεία προόδου.'},
  {'id': 'quality_q6',
   'prompt': 'Τι σημαίνει gated quiz;',
   'options': ['Quiz διαθέσιμο μόνο μετά τη σύνδεση', 'Quiz χωρίς ερωτήσεις', 'Quiz που ανοίγει CSS'],
   'answer': 'Quiz διαθέσιμο μόνο μετά τη σύνδεση',
   'hint': 'Gate σημαίνει έλεγχος πρόσβασης.',
   'explanation': 'Τα quiz κλειδώνουν ώστε η πρόοδος να συνδέεται με χρήστη.'},
  {'id': 'quality_q7',
   'prompt': 'Ποιος είναι στόχος του adaptive learning;',
   'options': ['Να προσαρμόζει πρόταση μάθησης με βάση επίδοση', 'Να αλλάζει τυχαία χρώματα', 'Να κρύβει όλες τις ενότητες'],
   'answer': 'Να προσαρμόζει πρόταση μάθησης με βάση επίδοση',
   'hint': 'Σκέψου επίδοση κάτω από 60 ή πάνω από 85.',
   'explanation': 'Η προσαρμογή βασίζεται στο σκορ και οδηγεί σε επανάληψη, συνέχεια ή πρόκληση.'},
  {'id': 'quality_q8',
   'prompt': 'Ποιο στοιχείο κάνει το UI πιο επαγγελματικό;',
   'options': ['Σαφής πλοήγηση και συνεπές layout', 'Τυχαία κουμπιά παντού', 'Απουσία feedback'],
   'answer': 'Σαφής πλοήγηση και συνεπές layout',
   'hint': 'Ο χρήστης πρέπει να καταλαβαίνει πού βρίσκεται.',
   'explanation': 'Το καλό UI καθοδηγεί τον χρήστη με συνέπεια και σαφήνεια.'}
]
