QUESTION_BANK = {'intro': [{'id': 'intro_q1',
            'prompt': 'Ποιος είναι ο κύριος ρόλος της JavaScript σε μία ιστοσελίδα;',
            'options': ['Να προσθέτει διαδραστική συμπεριφορά',
                        'Να αντικαθιστά το λειτουργικό σύστημα',
                        'Να συμπιέζει εικόνες'],
            'answer': 'Να προσθέτει διαδραστική συμπεριφορά',
            'hint': 'Σκέψου τι γίνεται όταν ο χρήστης πατά ένα κουμπί.',
            'explanation': 'Η JavaScript χρησιμοποιείται κυρίως για συμπεριφορά και αλληλεπίδραση μέσα στη σελίδα.'},
           {'id': 'intro_q2',
            'prompt': 'Ποια τεχνολογία περιγράφει κυρίως τη δομή μιας σελίδας;',
            'options': ['HTML', 'CSS', 'JavaScript'],
            'answer': 'HTML',
            'hint': 'Είναι η γλώσσα με tags όπως h1, p και button.',
            'explanation': 'Η HTML οργανώνει το περιεχόμενο και τη δομή της σελίδας.'},
           {'id': 'intro_q3',
            'prompt': "Τι εμφανίζει η εντολή console.log('test');",
            'options': ['Μήνυμα στην κονσόλα', 'Νέο αρχείο', 'CSS κανόνα'],
            'answer': 'Μήνυμα στην κονσόλα',
            'hint': 'Η console βοηθά στον έλεγχο και στο debugging.',
            'explanation': 'Η console.log γράφει μήνυμα στην κονσόλα.'},
           {'id': 'intro_q4',
            'prompt': 'Ποια τεχνολογία καθορίζει χρώματα και γραμματοσειρές;',
            'options': ['CSS', 'HTML', 'SQLite'],
            'answer': 'CSS',
            'hint': 'Αφορά την εμφάνιση.',
            'explanation': 'Η CSS είναι υπεύθυνη για την οπτική μορφοποίηση.'},
           {'id': 'intro_q5',
            'prompt': 'Ποιο είναι παράδειγμα διαδραστικότητας;',
            'options': ['Εμφάνιση μηνύματος μετά από click', 'Αποθήκευση εικόνας σε φάκελο', 'Αλλαγή ανάλυσης οθόνης'],
            'answer': 'Εμφάνιση μηνύματος μετά από click',
            'hint': 'Συνδέεται με ενέργεια χρήστη.',
            'explanation': 'Το click και η αντίδραση της σελίδας είναι διαδραστικότητα.'},
           {'id': 'intro_q6',
            'prompt': 'Πού μπορείς να δεις μηνύματα console.log στον browser;',
            'options': ['Στην κονσόλα developer tools', 'Στο αρχείο CSS', 'Στη βάση δεδομένων πάντα'],
            'answer': 'Στην κονσόλα developer tools',
            'hint': 'Άνοιξε τα εργαλεία προγραμματιστή.',
            'explanation': 'Τα console.log εμφανίζονται στην κονσόλα των developer tools.'}],
 'basics': [{'id': 'basics_q1',
             'prompt': 'Πότε προτιμάμε const αντί για let;',
             'options': ['Όταν δεν θέλουμε νέα ανάθεση της μεταβλητής',
                         'Όταν γράφουμε μόνο αριθμούς',
                         'Όταν θέλουμε υποχρεωτικά global μεταβλητή'],
             'answer': 'Όταν δεν θέλουμε νέα ανάθεση της μεταβλητής',
             'hint': 'Το const δηλώνει σταθερή αναφορά.',
             'explanation': 'Το const είναι κατάλληλο όταν δεν θα γίνει νέα ανάθεση.'},
            {'id': 'basics_q2',
             'prompt': 'Τι επιστρέφει η έκφραση 7 >= 5;',
             'options': ['true', 'false', "'7 >= 5'"],
             'answer': 'true',
             'hint': 'Είναι σύγκριση αριθμών.',
             'explanation': 'Το 7 είναι μεγαλύτερο ή ίσο με το 5.'},
            {'id': 'basics_q3',
             'prompt': 'Τι τύπος είναι το αποτέλεσμα μιας σύγκρισης;',
             'options': ['boolean', 'array', 'object πάντα'],
             'answer': 'boolean',
             'hint': 'Οι τιμές είναι true ή false.',
             'explanation': 'Οι συγκρίσεις επιστρέφουν boolean.'},
            {'id': 'basics_q4',
             'prompt': 'Ποιος τελεστής ελέγχει τιμή και τύπο;',
             'options': ['===', '=', '=>'],
             'answer': '===',
             'hint': 'Είναι αυστηρή ισότητα.',
             'explanation': 'Το === ελέγχει και τιμή και τύπο.'},
            {'id': 'basics_q5',
             'prompt': 'Ποια δομή χρησιμοποιούμε για απόφαση;',
             'options': ['if/else', 'font-size', 'href'],
             'answer': 'if/else',
             'hint': 'Εκτελεί διαφορετικό κώδικα ανά συνθήκη.',
             'explanation': 'Το if/else επιτρέπει αποφάσεις.'},
            {'id': 'basics_q6',
             'prompt': "Τι τύπος είναι η τιμή 'Μαρία';",
             'options': ['string', 'number', 'boolean'],
             'answer': 'string',
             'hint': 'Είναι κείμενο.',
             'explanation': 'Οι τιμές μέσα σε εισαγωγικά είναι strings.'}],
 'functions': [{'id': 'functions_q1',
                'prompt': 'Γιατί χρησιμοποιούμε συναρτήσεις;',
                'options': ['Για οργάνωση και επαναχρησιμοποίηση κώδικα',
                            'Για να κρύβουμε λάθη',
                            'Για να γράφουμε CSS'],
                'answer': 'Για οργάνωση και επαναχρησιμοποίηση κώδικα',
                'hint': 'Ομαδοποιούν λογική.',
                'explanation': 'Οι συναρτήσεις κάνουν τον κώδικα καθαρότερο.'},
               {'id': 'functions_q2',
                'prompt': 'Ποια λέξη επιστρέφει αποτέλεσμα από συνάρτηση;',
                'options': ['return', 'repeat', 'send'],
                'answer': 'return',
                'hint': 'Βγάζει τιμή από τη συνάρτηση.',
                'explanation': 'Η return επιστρέφει τιμή.'},
               {'id': 'functions_q3',
                'prompt': 'Στο function hello(name), τι είναι το name;',
                'options': ['parameter', 'argument', 'CSS selector'],
                'answer': 'parameter',
                'hint': 'Είναι το όνομα μέσα στον ορισμό.',
                'explanation': 'Το name είναι parameter.'},
               {'id': 'functions_q4',
                'prompt': "Στο hello('Άννα'), τι είναι το 'Άννα';",
                'options': ['argument', 'parameter', 'boolean'],
                'answer': 'argument',
                'hint': 'Είναι η πραγματική τιμή.',
                'explanation': "Το 'Άννα' είναι argument."},
               {'id': 'functions_q5',
                'prompt': 'Ποιο σύμβολο χαρακτηρίζει arrow function;',
                'options': ['=>', '===', '#'],
                'answer': '=>',
                'hint': 'Μοιάζει με βέλος.',
                'explanation': 'Το => χρησιμοποιείται στις arrow functions.'},
               {'id': 'functions_q6',
                'prompt': 'Τι είναι καλύτερο για επαναχρησιμοποιήσιμο αποτέλεσμα;',
                'options': ['return', 'console.log μόνο', 'alert πάντα'],
                'answer': 'return',
                'hint': 'Το αποτέλεσμα μπορεί να χρησιμοποιηθεί αλλού.',
                'explanation': 'Το return επιτρέπει επαναχρήση αποτελέσματος.'}],
 'arrays': [{'id': 'arrays_q1',
             'prompt': 'Τι είναι array;',
             'options': ['Λίστα τιμών', 'CSS χρώμα', 'HTML tag'],
             'answer': 'Λίστα τιμών',
             'hint': 'Περιέχει πολλά στοιχεία.',
             'explanation': 'Το array αποθηκεύει πολλές τιμές.'},
            {'id': 'arrays_q2',
             'prompt': 'Ποιο είναι το πρώτο index ενός array;',
             'options': ['0', '1', '-1'],
             'answer': '0',
             'hint': 'Η JavaScript μετρά από το μηδέν.',
             'explanation': 'Τα arrays ξεκινούν από index 0.'},
            {'id': 'arrays_q3',
             'prompt': 'Ποιο method κρατά στοιχεία που περνούν κριτήριο;',
             'options': ['filter', 'map', 'parse'],
             'answer': 'filter',
             'hint': 'Φιλτράρει.',
             'explanation': 'Το filter κρατά στοιχεία με βάση συνθήκη.'},
            {'id': 'arrays_q4',
             'prompt': 'Ποιο method δημιουργεί νέο array μετασχηματίζοντας τιμές;',
             'options': ['map', 'filter', 'alert'],
             'answer': 'map',
             'hint': 'Χαρτογραφεί κάθε στοιχείο σε νέα τιμή.',
             'explanation': 'Το map επιστρέφει νέο array.'},
            {'id': 'arrays_q5',
             'prompt': 'Ποιο method μπορεί να υπολογίσει άθροισμα;',
             'options': ['reduce', 'querySelector', 'JSON.parse'],
             'answer': 'reduce',
             'hint': 'Μειώνει array σε μία τιμή.',
             'explanation': 'Το reduce μπορεί να παράγει άθροισμα.'},
            {'id': 'arrays_q6',
             'prompt': 'Τι δείχνει το scores.length;',
             'options': ['Το πλήθος στοιχείων', 'Το πρώτο στοιχείο', 'Το χρώμα του array'],
             'answer': 'Το πλήθος στοιχείων',
             'hint': 'length σημαίνει μήκος.',
             'explanation': 'Το length επιστρέφει πλήθος στοιχείων.'}],
 'objects': [{'id': 'objects_q1',
              'prompt': 'Τι αναπαριστά ένα object;',
              'options': ['Οντότητα με ιδιότητες', 'Μόνο αριθμό', 'CSS κανόνα'],
              'answer': 'Οντότητα με ιδιότητες',
              'hint': 'Έχει key/value.',
              'explanation': 'Τα objects έχουν properties.'},
             {'id': 'objects_q2',
              'prompt': 'Πώς διαβάζουμε το name από student;',
              'options': ['student.name', 'student-name', 'student#name'],
              'answer': 'student.name',
              'hint': 'Dot notation.',
              'explanation': 'Με dot notation διαβάζουμε properties.'},
             {'id': 'objects_q3',
              'prompt': 'Τι κάνει το JSON.stringify;',
              'options': ['Μετατρέπει object σε JSON string', 'Αλλάζει CSS', 'Σβήνει array'],
              'answer': 'Μετατρέπει object σε JSON string',
              'hint': 'stringify σημαίνει μετατροπή σε string.',
              'explanation': 'Το JSON.stringify παράγει JSON text.'},
             {'id': 'objects_q4',
              'prompt': 'Τι κάνει το JSON.parse;',
              'options': ['Μετατρέπει JSON string σε τιμή JavaScript', 'Δημιουργεί event', 'Μετρά pixels'],
              'answer': 'Μετατρέπει JSON string σε τιμή JavaScript',
              'hint': 'parse σημαίνει ανάλυση κειμένου.',
              'explanation': 'Το JSON.parse διαβάζει JSON string.'},
             {'id': 'objects_q5',
              'prompt': 'Τι είναι property;',
              'options': ['Ιδιότητα object', 'Loop', 'Browser tab'],
              'answer': 'Ιδιότητα object',
              'hint': 'Π.χ. name ή score.',
              'explanation': 'Property είναι ιδιότητα σε object.'},
             {'id': 'objects_q6',
              'prompt': 'Ποια σύνταξη είναι destructuring;',
              'options': ['const { name } = student', 'const name => student', '#student.name'],
              'answer': 'const { name } = student',
              'hint': 'Χρησιμοποιεί άγκιστρα.',
              'explanation': 'Αυτή είναι σύνταξη object destructuring.'}],
 'dom_async': [{'id': 'dom_q1',
                'prompt': "Τι κάνει το document.querySelector('#title');",
                'options': ['Βρίσκει το πρώτο στοιχείο με id title', 'Δημιουργεί βάση', 'Σβήνει κουμπιά'],
                'answer': 'Βρίσκει το πρώτο στοιχείο με id title',
                'hint': 'Το # είναι selector για id.',
                'explanation': 'Το querySelector επιστρέφει DOM στοιχείο.'},
               {'id': 'dom_q2',
                'prompt': 'Ποιο event χρησιμοποιούμε για πάτημα κουμπιού;',
                'options': ['click', 'paint', 'loadData'],
                'answer': 'click',
                'hint': 'Περιγράφει πάτημα.',
                'explanation': 'Το click ενεργοποιείται με πάτημα.'},
               {'id': 'dom_q3',
                'prompt': 'Γιατί χρησιμοποιούμε preventDefault σε form submit;',
                'options': ['Για να μη γίνει αυτόματη ανανέωση σελίδας',
                            'Για να αλλάξει χρώμα',
                            'Για να φτιαχτεί array'],
                'answer': 'Για να μη γίνει αυτόματη ανανέωση σελίδας',
                'hint': 'Ελέγχουμε τη φόρμα με JS.',
                'explanation': 'Το preventDefault σταματά την προεπιλεγμένη συμπεριφορά.'},
               {'id': 'dom_q4',
                'prompt': 'Τι επιστρέφει συνήθως η fetch;',
                'options': ['Promise', 'CSS file', 'HTML tag'],
                'answer': 'Promise',
                'hint': 'Ασύγχρονη λειτουργία.',
                'explanation': 'Η fetch επιστρέφει Promise.'},
               {'id': 'dom_q5',
                'prompt': 'Ποια ιδιότητα αλλάζει κείμενο DOM στοιχείου;',
                'options': ['textContent', 'serverPort', 'databaseName'],
                'answer': 'textContent',
                'hint': 'Περιεχόμενο κειμένου.',
                'explanation': 'Το textContent αλλάζει κείμενο.'},
               {'id': 'dom_q6',
                'prompt': 'Τι κάνει το await;',
                'options': ['Περιμένει Promise μέσα σε async function', 'Δηλώνει CSS', 'Δημιουργεί object'],
                'answer': 'Περιμένει Promise μέσα σε async function',
                'hint': 'Συνδέεται με async.',
                'explanation': 'Το await περιμένει ολοκλήρωση Promise.'}],
 'debug_project': [{'id': 'debug_q1',
                    'prompt': 'Τι είναι syntax error;',
                    'options': ['Λάθος γραμματικής κώδικα', 'Χρώμα CSS', 'Επιτυχές quiz'],
                    'answer': 'Λάθος γραμματικής κώδικα',
                    'hint': 'Ο κώδικας δεν μπορεί να διαβαστεί σωστά.',
                    'explanation': 'Syntax error σημαίνει λάθος σύνταξης.'},
                   {'id': 'debug_q2',
                    'prompt': 'Ποιο εργαλείο βοηθά να δεις τιμή μεταβλητής;',
                    'options': ['console.log', 'border-radius', 'href'],
                    'answer': 'console.log',
                    'hint': 'Εμφανίζει στην κονσόλα.',
                    'explanation': 'Το console.log βοηθά στον έλεγχο τιμών.'},
                   {'id': 'debug_q3',
                    'prompt': 'Τι είναι state εφαρμογής;',
                    'options': ['Τα δεδομένα της τρέχουσας κατάστασης', 'Μόνο εικόνα', 'CSS font'],
                    'answer': 'Τα δεδομένα της τρέχουσας κατάστασης',
                    'hint': 'Π.χ. ενεργή ενότητα και score.',
                    'explanation': 'State είναι η τρέχουσα κατάσταση δεδομένων.'},
                   {'id': 'debug_q4',
                    'prompt': 'Πού κοιτάμε συχνά όταν κάτι δεν δουλεύει στον browser;',
                    'options': ['Developer console', 'Μόνο στο wallpaper', 'Στο πληκτρολόγιο'],
                    'answer': 'Developer console',
                    'hint': 'Εμφανίζει errors.',
                    'explanation': 'Η κονσόλα δείχνει σφάλματα και logs.'},
                   {'id': 'debug_q5',
                    'prompt': 'Τι πρέπει να έχει ένα ολοκληρωμένο quiz app;',
                    'options': ['Ερωτήσεις, υποβολή, score και feedback', 'Μόνο χρώμα φόντου', 'Μόνο τίτλο'],
                    'answer': 'Ερωτήσεις, υποβολή, score και feedback',
                    'hint': 'Σκέψου τη ροή χρήστη.',
                    'explanation': 'Ένα quiz app χρειάζεται περιεχόμενο, αλληλεπίδραση και ανατροφοδότηση.'},
                   {'id': 'debug_q6',
                    'prompt': 'Ποια στρατηγική είναι χρήσιμη στο debugging;',
                    'options': ['Έλεγχος μικρών βημάτων', 'Τυχαίες αλλαγές παντού', 'Διαγραφή όλου του κώδικα'],
                    'answer': 'Έλεγχος μικρών βημάτων',
                    'hint': 'Απομονώνουμε το πρόβλημα.',
                    'explanation': 'Το debugging γίνεται καλύτερα με μικρά, ελεγχόμενα βήματα.'}]}
